export const preSpecPatterns = [
    'эп. aor.',
    'эп. impf.',
    'эп. 1 л. pl. aor.',
    'aor. med.',
    'ион. aor.',
    'aor. к',
    'impf. к',
    'gen. pl. к',
    'gen. sing. к',
    'dat. к',
    'эп. dat. pl.',
    'ион.-дор. =',
    'pf. pass. к',
    'pf. к',
    'эп. ',
    'aor. к',
    'inf. к',
    'pf. pass. к',
    'эп. aor. 1 к',
    'эп. impf. к',
    'aor. к',
    'эп. aor. к',
    'эп. 1 л. pl. aor. к',
    'aor. med. к',
    'ион. aor. к',
    'aor. к',
    'impf. к',
    'gen. pl. к',
    'gen. sing. к',
    'dat. к',
    'fut. к',
    'part. aor. pl. к',
    'gen. к',
    'pl. к',
    'эп.-ион. gen. к',
    'acc. pl. к',
    'gen. к',
    'part. aor. pass. к',
    'aor. 1',
    'ppf. med. к',
    'acc. к',
    'part. pass. к',
    'pf. med. и pass. к',
    'acc. sing. к',
    'impf. med. к',
    'aor. pass. к',
    'impf. iter. к',
    'part. praes. к',
    'imper. praes. к',
    'imper. к',
    'part. praes. n к',
    'inf. med. к',
    'fut. opt. к',
    'opt. к',
    'n к',
    'стяж. к',
    'fut. med. к',
    'pass. к',
    'dat. dual. к',
    'inf. praes. к',
    'voc. к',
    'pf.-praes. к',
    'pf. med. к',
    'dat. sing. к',
    'aor. iter.',
    'part. к',
    'aor. sing. к',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    'только praes.',
    '',
    '',
    '',
    '',
    '',
    '',
    'тж. раздельно',
    'в произнош. скифа',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    'f к',
    'стяж. =',
    'атт.',
    'эол.',
    'ион. =',
    'дор. =',
    'дор.',
    'ион.',
    'скиф.',
    'эп.-поэт.',
    'беот.',
    'лак.',
    '',
    '',
    '',
    '',

]
